---
abstract: "Parse the F<USERINFO/> files in MediaWiki's Subversion repository"
author:
  - 'Ævar Arnfjörð Bjarmason <avar@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.11
generated_by: 'Dist::Zilla version 1.100660'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: MediaWiki-USERINFO
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  Data::Dump: 0
  Email::Valid: 0
  List::MoreUtils: 0
  Moose: 0.94
  MooseX::Getopt: 0.26
  MooseX::Getopt::Dashes: 0
  MooseX::StrictConstructor: 0.08
  MooseX::Types: 0.21
  MooseX::Types::Moose: 0.21
  MooseX::Types::Path::Class: 0.05
  Test::More: 0.88
  Test::utf8: 0
  YAML::Syck: 0
  autodie: 0
  namespace::clean: 0
  perl: 5.010
resources:
  Ratings: http://cpanratings.perl.org/d/MediaWiki-USERINFO
  bugtracker: http://github.com/avar/mediawiki-userinfo/issues
  homepage: http://search.cpan.org/dist/MediaWiki-USERINFO/
  license: http://dev.perl.org/licenses/
  repository: http://github.com/avar/mediawiki-userinfo
version: 0.01
