---
abstract: "Parse the F<USERINFO/> files in MediaWiki's Subversion repository"
author:
  - 'Ævar Arnfjörð Bjarmason <avar@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.11
generated_by: 'Dist::Zilla version 1.100660'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: MediaWiki-USERINFO
no_index:
  directory:
    - t
requires:
  Email::Valid: 0
  Encode: 0
  File::Slurp: 0
  File::Spec::Functions: 0
  File::Temp: 0
  IPC::System::Simple: 0
  List::MoreUtils: 0
  Moose: 0
  MooseX::Getopt::Dashes: 0
  MooseX::StrictConstructor: 0
  MooseX::Types::Moose: 0
  Test::More: 0
  Test::utf8: 0
  YAML::Syck: 0
  autodie: 0
  namespace::clean: 0
  perl: 5.10.0
resources:
  Ratings: http://cpanratings.perl.org/d/MediaWiki-USERINFO
  bugtracker: http://github.com/avar/mediawiki-userinfo/issues
  homepage: http://search.cpan.org/dist/MediaWiki-USERINFO/
  license: http://dev.perl.org/licenses/
  repository: http://github.com/avar/mediawiki-userinfo
version: 0.03
